FROM node:14.17 as builder

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV mainnet

COPY package.json package-lock.json /app/

RUN npm install

COPY . /app/

RUN npm run build

#ngix Web Server
FROM nginx:1.15.7-alpine
COPY --from=builder /app/build /usr/share/nginx/html
ADD nginx.default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

