FROM node:14.17 as builder

EXPOSE 80

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV testnet

COPY package.json package-lock.json /app/

RUN npm install

COPY . /app/

RUN npm run build

CMD ["npm", "start"]
